// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  moduleName: "Home",
  moduleGroup: "Page",
  uri: "HomePage",
  props: {
    view: "vue",
    route: {
      path: ""
    }
  },
  routes: [
    {
      actionName: "index",
      uri: "HomePage.index",
      middlewares: [
        {
          name: "route",
          props: {
            methods: [
              "GET"
            ],
            path: ""
          }
        }
      ]
    }
  ],
  SavRoute: {
    uri: "HomePage",
    path: "/",
    childs: [
      {
        uri: "HomePage.index",
        path: "/",
        methods: [
          "GET"
        ],
        relative: ""
      }
    ],
    parents: []
  },
  VueRoute: {
    component: "Home/Home",
    path: "/",
    children: [
      {
        component: "Home/HomeIndex",
        name: "HomeIndex",
        path: "",
        methods: [
          "GET"
        ]
      }
    ]
  }
}
