// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
import Home from './Home/Home.vue'
import HomeIndex from './Home/HomeIndex.vue'

Home.name = 'Home'
HomeIndex.name = 'HomeIndex'

export default [
  {
    component: Home,
    path: "/",
    children: [
      {
        component: HomeIndex,
        name: "HomeIndex",
        path: "",
        methods: [
          "GET"
        ]
      }
    ]
  }
]
